import './globals.css'
import "@arco-design/web-react/dist/css/arco.css";

export const metadata = {
  title: 'faceMesh',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon_2.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
